Vendor 2025-09-04 v244

diff --git a/.github/workflows/vendor.yml b/.github/workflows/vendor.yml
--- a/.github/workflows/vendor.yml
+++ b/.github/workflows/vendor.yml
@@ -50,56 +50,76 @@ jobs:
   validate:
     runs-on: ubuntu-24.04
     outputs:
-      prefix: ${{ inputs.prefix }}
-      host: ${{ inputs.host }}
-      channel: ${{ inputs.channel }}
-      version: ${{ inputs.version }}
-      matrix: ${{ steps.generate_matrix.outputs.JSON }}
+      prefix: ${{ steps.validate_prefix.outputs.prefix }}
+      host: ${{ steps.validate_host.outputs.host }}
+      channel: ${{ steps.validate_channel.outputs.channel }}
+      version: ${{ steps.validate_version.outputs.version }}
+      matrix: ${{ steps.generate_matrix.outputs.matrix }}
     steps:
       - name: Validate prefix value
         id: validate_prefix
         run: |
-          if [[ ! "${{ inputs.prefix }}" =~ ^[0-9a-zA-Z]+$ ]]; then
-            echo "::error input=prefix,value=${{ inputs.prefix }}::Invalid prefix value"
+          PREFIX="$(echo "${{ inputs.prefix }}" | xargs)"
+          if [[ ! "${PREFIX}" =~ ^[0-9a-zA-Z]+$ ]]; then
+            echo "::error input=prefix,value=${PREFIX}::Invalid prefix value"
             exit 1
           fi
+          echo "prefix=${PREFIX}" >> $GITHUB_OUTPUT
       - name: Validate host value
         id: validate_host
         run: |
-          if [[ -z "$(echo "${{ inputs.host }}" | grep -P '(?=^.{1,254}$)(^(?>(?!\d+\.)[a-zA-Z0-9_\-]{1,63}\.?)+(?:[a-zA-Z]{2,})$)')" ]]; then
-            echo "::error input=host,value=${{ inputs.host }}::Invalid host value"
+          HOST="$(echo "${{ inputs.host }}" | xargs)"
+          if [[ -z "$(echo "${HOST}" | grep -P '(?=^.{1,254}$)(^(?>(?!\d+\.)[a-zA-Z0-9_\-]{1,63}\.?)+(?:[a-zA-Z]{2,})$)')" ]]; then
+            echo "::error input=host,value=${HOST}::Invalid host value"
             exit 1
           fi
+          echo "host=${HOST}" >> $GITHUB_OUTPUT
+      - name: Validate channel value
+        id: validate_channel
+        run: |
+          CHANNEL="$(echo "${{ inputs.channel }}" | xargs)"
+          readarray -d ',' -t CHANNELS < <(printf '%s' "${CHANNEL}")
+          for CHANNEL in ${CHANNELS[@]}; do
+            if [[ ! ( "${CHANNEL}" == "stable" || "${CHANNEL}" == "testing" ) ]]; then
+              echo "::error input=channel,value=${CHANNEL}::Invalid channel value"
+              exit 1
+            fi
+          done
+          printf -v CHANNEL '%s,' "${CHANNELS[@]}"
+          echo "channel=${CHANNEL%,}" >> $GITHUB_OUTPUT
       - name: Validate version value
         id: validate_version
         run: |
-          if [[ -n "${{ inputs.version }}" ]]; then
-            if [[ "${{ inputs.channel }}" == *","* ]]; then
-              echo "::error input=version,value=${{ inputs.version }}::Same version value can't apply to multiple channels"
+          VERSION="$(echo "${{ inputs.version }}" | xargs)"
+          CHANNEL="$(echo "${{ steps.validate_channel.outputs.channel }}" | xargs)"
+          if [[ -n "${VERSION}" ]]; then
+            if [[ "${CHANNEL}" == *","* ]]; then
+              echo "::error input=version,value=${VERSION}::Same version value can't apply to multiple channels"
               exit 1
-            fi
-            if [[ "${{ inputs.channel }}" == "stable" ]]; then
-              if [[ ! "${{ inputs.version }}" =~ ^7\.[0-9]+(\.[0-9]+)?$ ]]; then
-                echo "::error input=version,value=${{ inputs.version }}::Invalid version value for the stable channel"
+            elif [[ "${CHANNEL}" == "stable" ]]; then
+              if [[ ! "${VERSION}" =~ ^7\.[0-9]+(\.[0-9]+)?$ ]]; then
+                echo "::error input=version,value=${VERSION}::Invalid version value for the ${CHANNEL} channel"
                 exit 1
               fi
-            fi
-            if [[ "${{ inputs.channel }}" == "testing" ]]; then
-              if [[ ! "${{ inputs.version }}" =~ ^7\.[0-9]+(\.[0-9]+)?(alpha|beta|rc)[0-9]+$ ]]; then
-                echo "::error input=version,value=${{ inputs.version }}::Invalid version value for the testing channel"
+            elif [[ "${CHANNEL}" == "testing" ]]; then
+              if [[ ! "${VERSION}" =~ ^7\.[0-9]+(\.[0-9]+)?(ab|beta|rc)[0-9]+$ ]]; then
+                echo "::error input=version,value=${VERSION}::Invalid version value for the ${CHANNEL} channel"
                 exit 1
               fi
+            else
+              echo "::warning::Unknown channel value, so version value has not been validated"
             fi
           fi
+          echo "version=${VERSION}" >> $GITHUB_OUTPUT
       - name: Generate matrix using channel and version values
         id: generate_matrix
         run: |
-          readarray -d ',' -t CHANNELS < <(printf '%s' "${{ inputs.channel }}")
-          VERSION="${{ inputs.version }}"
+          readarray -d ',' -t CHANNELS < <(printf '%s' "${{ steps.validate_channel.outputs.channel }}")
+          VERSION="${{ steps.validate_version.outputs.version }}"
           JSON=""
           for CHANNEL in ${CHANNELS[@]}; do
             if [[ -z "${VERSION}" ]]; then
-              VERSION_URL="https://${{ inputs.host }}/routeros/NEWESTa7.${CHANNEL}"
+              VERSION_URL="https://${{ steps.validate_host.outputs.host }}/routeros/NEWESTa7.${CHANNEL}"
               echo "::debug::VERSION_URL=${VERSION_URL}"
               VERSION="$(wget -nv -O - ${VERSION_URL} | cut -d ' ' -f1)"
               echo "::debug::VERSION=${VERSION}"
@@ -108,7 +128,7 @@ jobs:
             JSON="${JSON}{\"channel\":\"${CHANNEL}\",\"version\":\"${VERSION}\"}"
           done
           JSON="[${JSON}]"
-          echo "JSON=${JSON}" >> $GITHUB_OUTPUT
+          echo "matrix=${JSON}" >> $GITHUB_OUTPUT
   download:
     needs: validate
     runs-on: ubuntu-24.04
