Changes v375

diff --git a/.github/workflows/vendor.yml b/.github/workflows/vendor.yml
--- a/.github/workflows/vendor.yml
+++ b/.github/workflows/vendor.yml
@@ -472,7 +472,7 @@ jobs:
             gh api --method DELETE \
               -H "Accept: application/vnd.github+json" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
-              /repos/${{ github.repository }}/releases/${ID}
+              /repos/${{ github.repository }}/releases/${ID} || echo 'warning: Failed to delete an existing release'
           fi
           FOUND='true'
           REF="$(gh api \
@@ -484,7 +484,7 @@ jobs:
             gh api --method DELETE \
               -H "Accept: application/vnd.github+json" \
               -H "X-GitHub-Api-Version: 2022-11-28" \
-              /repos/${{ github.repository }}/git/ref/tags/${{ env.tag }}
+              /repos/${{ github.repository }}/git/refs/tags/${{ env.tag }} || echo 'warning: Failed to delete an existing tag'
           fi
 
       - name: Upload release files as artifacts
